# Generated by Django 5.0.6 on 2024-05-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_good_standing',
            new_name='billable',
        ),
    ]
