# Generated by Django 5.0.6 on 2024-06-03 15:34

from django.db import migrations, models
from boxes.models import PACKAGE_STATES


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageSystemTrackingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='INT', max_length=3)),
                ('last_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='current_state',
            field=models.PositiveSmallIntegerField(choices=PACKAGE_STATES, default=0),
        ),
        migrations.AlterField(
            model_name='packageledger',
            name='state',
            field=models.PositiveSmallIntegerField(choices=PACKAGE_STATES),
        ),
    ]
