# Generated by Django 5.0.6 on 2024-06-03 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_packagesystemtrackingcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicklistQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picklist', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='boxes.picklist')),
                ('queue', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='boxes.queue')),
            ],
        ),
    ]
