# Generated by Django 5.0.6 on 2024-06-05 21:11

import boxes.management.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_picklistqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address1', models.CharField(max_length=64)),
                ('address2', models.CharField(max_length=64)),
                ('website', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('source_image', models.ImageField(storage=boxes.management.custom_storage.OverwriteStorage(), upload_to='images/')),
                ('login_image', models.ImageField(storage=boxes.management.custom_storage.OverwriteStorage(), upload_to='images/')),
                ('label_image', models.ImageField(storage=boxes.management.custom_storage.OverwriteStorage(), upload_to='images/')),
                ('navbar_image', models.ImageField(storage=boxes.management.custom_storage.OverwriteStorage(), upload_to='images/')),
                ('favicon_image', models.ImageField(storage=boxes.management.custom_storage.OverwriteStorage(), upload_to='images/')),
            ],
        ),
    ]
