# Generated by Django 5.0.6 on 2024-06-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0005_globalsettings_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='email_sending',
            field=models.BooleanField(default=True),
        ),
    ]
