# Generated by Django 5.0.6 on 2024-06-21 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0007_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_path', models.CharField(blank=True, max_length=512, null=True)),
                ('last_success', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='boxes.report')),
            ],
        ),
    ]
