# Generated by Django 5.0.6 on 2024-06-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0008_reportresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportresult',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
