# Generated by Django 5.0.6 on 2024-06-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0009_reportresult_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('T', 'Today'), ('W', 'Week'), ('M', 'Month'), ('Q', 'Quarter'), ('Y', 'Year')])),
                ('last_updated', models.DateTimeField()),
                ('chart_data', models.JSONField(null=True)),
                ('total_data', models.JSONField()),
            ],
        ),
    ]
