# Generated by Django 5.0.6 on 2024-07-02 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0010_chart'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boxes.account')),
            ],
        ),
        migrations.CreateModel(
            name='StripePaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_id', models.CharField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boxes.accountstripecustomer')),
            ],
        ),
    ]
