# Generated by Django 5.0.7 on 2024-07-16 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0011_accountstripecustomer_stripepaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_intent_id', models.CharField(null=True)),
                ('current_state', models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Requires Action'), (2, 'Processing'), (3, 'Succeeded'), (4, 'Failed')], default=0)),
                ('line_items', models.JSONField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stripe_fee', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('deposit_total', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boxes.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accountledger',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='boxes.invoice'),
        ),
    ]
