# Generated by Django 5.0.7 on 2024-07-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0012_package_paid_invoice_accountledger_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='pass_on_fees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='tax_stripe_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='taxes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='processing_fees',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
