# Generated by Django 6.0.3 on 2026-03-26 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0013_globalsettings_pass_on_fees_globalsettings_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(1), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountalias',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.account'),
        ),
        migrations.AlterField(
            model_name='accountchargesettings',
            name='package_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boxes.packagetype'),
        ),
        migrations.AlterField(
            model_name='accountstripecustomer',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.account'),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.package'),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.emailtemplate'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.account'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packagepicklist',
            name='package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boxes.package'),
        ),
        migrations.AlterField(
            model_name='packagepicklist',
            name='picklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.picklist'),
        ),
        migrations.AlterField(
            model_name='packagequeue',
            name='package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boxes.package'),
        ),
        migrations.AlterField(
            model_name='packagequeue',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.queue'),
        ),
        migrations.AlterField(
            model_name='picklistqueue',
            name='picklist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boxes.picklist'),
        ),
        migrations.AlterField(
            model_name='picklistqueue',
            name='queue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boxes.queue'),
        ),
        migrations.AlterField(
            model_name='reportresult',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boxes.report'),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.account'),
        ),
        migrations.AlterField(
            model_name='sentemailcontents',
            name='sent_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.sentemail'),
        ),
        migrations.AlterField(
            model_name='sentemailpackage',
            name='sent_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.sentemail'),
        ),
        migrations.AlterField(
            model_name='sentemailresult',
            name='sent_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.sentemail'),
        ),
        migrations.AlterField(
            model_name='stripepaymentmethod',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.accountstripecustomer'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.account'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
