# Generated by Django 6.0.3 on 2026-07-13 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0014_alter_account_user_alter_accountalias_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boxes.account'),
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boxes.invoice'),
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boxes.package'),
        ),
        migrations.AlterField(
            model_name='customuseremail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packageledger',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.package'),
        ),
        migrations.AlterField(
            model_name='packageledger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sentemailpackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.package'),
        ),
    ]
