# Generated by Django 6.0.7 on 2026-07-13 14:51

from django.db import migrations, models


def set_staff_flag_from_groups(apps, schema_editor):
    """Align AbstractUser.is_staff with Staff/Admin group membership."""
    CustomUser = apps.get_model("boxes", "CustomUser")
    CustomUser.objects.filter(groups__name__in=["Staff", "Admin"]).update(is_staff=True)


class Migration(migrations.Migration):

    dependencies = [
        ("boxes", "0015_alter_accountbalance_account_alter_accountledger_invoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.RunPython(set_staff_flag_from_groups, migrations.RunPython.noop),
    ]
