# Generated by Django 6.0.7 on 2026-07-15 14:04

import boxes.models.account
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0016_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(boxes.models.account._account_user_on_delete), to=settings.AUTH_USER_MODEL),
        ),
    ]
