# Generated by Django 6.0.7 on 2026-07-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0018_useraccount_membership_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='allow_duplicate_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carrier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='packagetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_code',
            field=models.CharField(max_length=30),
        ),
    ]
