# Generated by Django 6.0.7 on 2026-07-15 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0019_carrier_packagetype_active_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField()),
                ('message_uuid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('sent_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='boxes.sentemail')),
            ],
            options={
                'indexes': [models.Index(fields=['message_uuid', 'event_type'], name='boxes_sente_message_b62b6c_idx')],
            },
        ),
    ]
