# Generated by Django 6.0.7 on 2026-07-15 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0020_sentemailevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupScheduleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('weekly', 'Weekly')], default='none', max_length=16)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PickupDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('picklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_days', to='boxes.picklist')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PackagePickupReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_reservation', to='boxes.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_reservations', to=settings.AUTH_USER_MODEL)),
                ('pickup_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='boxes.pickupday')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
