# Generated by Django 6.0.7 on 2026-07-21 16:35

import boxes.models.signup
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0022_create_delivery_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=boxes.models.signup.generate_invite_token, max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('middle_name', models.CharField(blank=True, default='', max_length=64)),
                ('prefix', models.CharField(blank=True, default='', max_length=16)),
                ('suffix', models.CharField(blank=True, default='', max_length=16)),
                ('company', models.CharField(blank=True, default='', max_length=128)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=20)),
                ('role', models.CharField(default='owner', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=boxes.models.signup.default_invite_expiry)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=512)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_invites', to='boxes.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_signup_invites', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_signup_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'used_at'], name='boxes_signu_email_1af5e1_idx')],
            },
        ),
    ]
