# Generated by Django 6.0.7 on 2026-07-21 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0023_signup_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boxes.account'),
        ),
    ]
