image: ubuntu:24.04

services:
  - name: postgres:16
    alias: postgres
  - name: rabbitmq:3.12-management
    alias: rabbitmq

variables:
  POSTGRES_DB: test_db
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  DB_HOST: postgres
  DB_NAME: test_db
  DB_USER: user
  DB_PASSWORD: password
  DB_PORT: 5432
  DB_ENGINE: django.db.backends.postgresql
  CELERY_BROKER_USER: boxes
  CELERY_BROKER_PASSWORD: password
  CELERY_BROKER_VHOST: boxes_host
  CELERY_BROKER_HOST: rabbitmq
  RABBITMQ_DEFAULT_USER: boxes
  RABBITMQ_DEFAULT_PASSWORD: password
  RABBITMQ_DEFAULT_VHOST: boxes_host
  RABBITMQ_DEFAULT_PORT: 5672

stages:
  - build

before_script:
  - apt-get update && apt-get -y install python3-virtualenv python3-psycopg

cache:
  paths:
    - .env

build:
  stage: build
  script:
    # Setup RabbitMQ
    - apt-get update && apt-get install -y curl wait-for-it
    - wait-for-it rabbitmq:15672 -- echo "RabbitMQ is up"
    - >
      curl -u guest:guest -X PUT -H "Content-Type: application/json" 
      -d '{"password":"password","tags":"administrator"}' 
      "http://rabbitmq:15672/api/users/boxes"
    - >
      curl -u guest:guest -X PUT -H "Content-Type: application/json" 
      -d '{"configure":".*","write":".*","read":".*"}' 
      "http://rabbitmq:15672/api/permissions/boxes_host/boxes"
    # Set up the instance
    - ./setup.sh dev
    - env/bin/celery -A boxes worker --concurrency=1 -E
