image: ubuntu:24.04

services:
  - name: postgres:16
    alias: postgres
  - name: rabbitmq:3.12
    alias: rabbitmq

variables:
  POSTGRES_DB: "test_db"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  DB_HOST: "postgres"
  DB_NAME: "test_db"
  DB_USER: "user"
  DB_PASSWORD: "password"
  DB_PORT: 5432
  DB_ENGINE: "django.db.backends.postgresql"
  CELERY_BROKER_USER: "boxes"
  CELERY_BROKER_PASSWORD: "changem3"
  CELERY_BROKER_VHOST: "boxes_host"
  CELERY_BROKER_HOST: "rabbitmq"

stages:
  - setup
  - build

before_script:
  - apt-get update && apt-get -y install python3-virtualenv

cache:
  paths:
    - .env

setup_rabbitmq:
  stage: setup
  script:
    - apt-get update && apt-get install -y curl
    - curl -u $CELERY_BROKER_USER:$CELERY_BROKER_PASS -X PUT -d "password=$CELERY_BROKER_PASSWORD&tags=administrator" "http://rabbitmq:15672/api/users/$CELERY_BROKER_USER"
    - curl -u $CELERY_BROKER_USER:$CELERY_BROKER_PASS -X PUT -d "configure=.*&write=.*&read=.*" "http://rabbitmq:15672/api/permissions/$CELERY_BROKER_VHOST/$CELERY_BROKER_USER"

build:
  stage: build
  script:
    - ./setup.sh dev
