"""Pickup day availability: schedule expansion and open-day windows."""
from __future__ import annotations

import logging
from datetime import date, timedelta
from typing import Iterable, Optional

from django.db import transaction

from boxes.models import (
    EmailQueue,
    EmailTemplate,
    PackagePickupReservation,
    PickupDay,
    PickupScheduleRule,
)

logger = logging.getLogger(__name__)


def expand_schedule_rule(
    rule: PickupScheduleRule, window_start: date, window_end: date
) -> set[date]:
    """Return dates generated by a single rule inside [window_start, window_end].

    Inactive rules yield nothing. Window is inclusive on both ends.
    """
    if not rule.is_active or window_start > window_end:
        return set()

    # Effective generation range is intersection of rule span and query window
    rule_start = max(rule.start_date, window_start)
    rule_end = rule.end_date if rule.end_date is not None else window_end
    rule_end = min(rule_end, window_end)
    if rule_start > rule_end:
        return set()

    if rule.recurrence == PickupScheduleRule.RECURRENCE_NONE:
        # Single occurrence on start_date when it falls in the intersection
        if rule_start <= rule.start_date <= rule_end:
            return {rule.start_date}
        return set()

    if rule.recurrence == PickupScheduleRule.RECURRENCE_WEEKLY:
        if rule.weekday is None:
            return set()
        cursor = rule_start
        delta = (rule.weekday - cursor.weekday()) % 7
        cursor = cursor + timedelta(days=delta)
        dates: set[date] = set()
        while cursor <= rule_end:
            dates.add(cursor)
            cursor += timedelta(days=7)
        return dates

    return set()


def expand_schedule_rules(
    window_start: date,
    window_end: date,
    rules: Optional[Iterable[PickupScheduleRule]] = None,
) -> set[date]:
    """Union of dates from active schedule rules in the inclusive window."""
    if rules is None:
        rules = PickupScheduleRule.objects.filter(is_active=True)
    result: set[date] = set()
    for rule in rules:
        result |= expand_schedule_rule(rule, window_start, window_end)
    return result


def list_open_pickup_dates(
    window_start: date,
    window_end: date,
    rules: Optional[Iterable[PickupScheduleRule]] = None,
) -> list[date]:
    """Open pickup dates in [window_start, window_end], sorted ascending.

    Candidates come from schedule rules plus explicit active PickupDay rows.
    Any PickupDay with is_active=False is removed (inactive override).
    """
    candidates = expand_schedule_rules(window_start, window_end, rules=rules)

    day_rows = PickupDay.objects.filter(date__gte=window_start, date__lte=window_end)
    for day in day_rows:
        if day.is_active:
            candidates.add(day.date)
        else:
            candidates.discard(day.date)

    return sorted(candidates)


def list_open_pickup_days(
    window_start: date,
    window_end: date,
    rules: Optional[Iterable[PickupScheduleRule]] = None,
    ensure_rows: bool = False,
) -> list[PickupDay]:
    """Return persisted PickupDay rows for open dates in the window.

    With ensure_rows=True, missing open dates are created as active days.
    Without it, only dates that already have a PickupDay row are returned.
    """
    open_dates = list_open_pickup_dates(window_start, window_end, rules=rules)
    existing = {
        d.date: d
        for d in PickupDay.objects.filter(date__in=open_dates)
    }
    result: list[PickupDay] = []
    for d in open_dates:
        if d in existing:
            result.append(existing[d])
        elif ensure_rows:
            day, _ = PickupDay.objects.get_or_create(
                date=d,
                defaults={"is_active": True},
            )
            result.append(day)
    return result


def get_or_create_open_pickup_day(target: date) -> PickupDay:
    """Return an active PickupDay for target if that date is open.

    Raises ValueError when the date is not an open pickup day.
    """
    open_dates = list_open_pickup_dates(target, target)
    if target not in open_dates:
        raise ValueError(f"{target.isoformat()} is not an open pickup day")
    day, _ = PickupDay.objects.get_or_create(date=target, defaults={"is_active": True})
    if not day.is_active:
        raise ValueError(f"{target.isoformat()} is not an open pickup day")
    return day


@transaction.atomic
def set_pickup_day_active(pickup_day: PickupDay, is_active: bool) -> PickupDay:
    """Set is_active on a day; when deactivating with reservations, notify."""
    was_active = pickup_day.is_active
    pickup_day.is_active = is_active
    pickup_day.save(update_fields=["is_active"])

    if was_active and not is_active:
        reservation_count = PackagePickupReservation.objects.filter(
            pickup_day=pickup_day
        ).count()
        if reservation_count:
            from boxes.tasks.pickup import notify_pickup_day_cancelled

            logger.info(
                "Pickup day %s deactivated with %s reservation(s); enqueueing notify",
                pickup_day.date,
                reservation_count,
            )
            notify_pickup_day_cancelled.delay(pickup_day.id)

    return pickup_day


def enqueue_pickup_cancellation_emails(pickup_day: PickupDay) -> int:
    """Enqueue EmailQueue rows for reserved packages when a day is cancelled.

    Looks up template named "Pickup Day Cancelled". If missing, logs and
    returns 0. Returns number of queue rows created.
    """
    template = EmailTemplate.objects.filter(name="Pickup Day Cancelled").first()
    if template is None:
        logger.warning(
            'No EmailTemplate named "Pickup Day Cancelled"; skip queue for day %s',
            pickup_day.date,
        )
        return 0

    package_ids = list(
        PackagePickupReservation.objects.filter(pickup_day=pickup_day).values_list(
            "package_id", flat=True
        )
    )
    created = 0
    for package_id in package_ids:
        _, was_created = EmailQueue.objects.get_or_create(
            package_id=package_id,
            template=template,
        )
        if was_created:
            created += 1
    return created
